#!/usr/bin/env bash

ALIYA=${ALIYA:-~/Aliya}
export ALIYA=$ALIYA
export PATH="$ALIYA/bin:$PATH"

[ "$WSL_DISTRO_NAME" ] && {
    WIN_HOST=$(ip route | awk '{print $3; exit}')
    export WIN_HOST=$WIN_HOST
    export LIBGL_ALWAYS_INDIRECT=1
    export DISPLAY=$WIN_HOST:0
}

[ -d "$ALIYA/app/roswell" ] && {
    export ROSWELL_HOME="$ALIYA/app/roswell"
    export PATH="$ROSWELL_HOME/bin:$PATH"
}

[ -d "$ALIYA/app/ohmyzsh" ] && [ $ZSH_VERSION ] && {
    source "$ALIYA/etc/zshrc"
}

[ -d "$ALIYA/app/pyenv" ] && {
    export PYENV_ROOT="$ALIYA/app/pyenv" 
    export PATH="$PYENV_ROOT/bin:$PATH" 
    if command -v pyenv 1>/dev/null 2>&1; then
        eval "$(pyenv init --path)"
        eval "$(pyenv init -)"
    fi
}

[ -d "$ALIYA/app/lemacs" ] && {
    export LEMACS="$ALIYA/app/lemacs"
    export PATH="$LEMACS/bin:$PATH"
}

[ -d "$ALIYA/app/roswell" ] && {
    export ROSWELL="$ALIYA/app/roswell"
    export PATH="$ROSWELL/bin:$PATH"
}

[ -d "$ALIYA/app/nvm" ] && {
    export NVM_DIR="$ALIYA/app/nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
    [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
}

function proxy-on() {
    if [ $WIN_HOST ] ;then
        PROXY="http://$WIN_HOST:1081"
    else
        PROXY="http://localhost:1081"
    fi

    export http_proxy=$PROXY
    export https_proxy=$PROXY
    git config --global http.proxy $PROXY
    git config --global https.proxy $PROXY
}

function proxy-off() {
    unset http_proxy
    unset https_proxy
    git config --global --unset http.proxy
    git config --global --unset https.proxy
}
